CREATE TABLE USER (UID INTEGER PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(30));
CREATE TABLE CARDS (CID INTEGER PRIMARY KEY AUTO_INCREMENT, FRONT VARCHAR(255) NOT NULL, BACK VARCHAR(255) NOT NULL);
CREATE TABLE TAGS (TID INTEGER PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(30));
CREATE TABLE HASTAGS (CID INTEGER, TID INTEGER);
CREATE TABLE DECKS (DID INTEGER PRIMARY KEY  AUTO_INCREMENT,  NAME VARCHAR(50)) ;
CREATE TABLE HASCARDS (DID INTEGER,  CID INTEGER);
CREATE TABLE ANSWERS (AID INTEGER PRIMARY KEY  AUTO_INCREMENT, TOTALTIME INTEGER, CORRECTNESS BOOLEAN, DATE TEXT);
CREATE TABLE USERANSWERS(UID INTEGER, CID INTEGER, AID INTEGER);
CREATE TABLE USERDECKS (UID INTEGER, DID INTEGER);
